{{- if and .Values.podDisruptionBudget.enabled (ne (include "latr.multiAccount" .) "true") }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "latr.fullname" . }}
  labels:
    {{- include "latr.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "latr.selectorLabels" . | nindent 6 }}
{{- end }}
{{- if and .Values.podDisruptionBudget.enabled (eq (include "latr.multiAccount" .) "true") }}
{{- range $account := .Values.accounts }}
{{- $ctx := dict "root" $ "account" $account }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "latr.accountFullname" $ctx }}
  labels:
    {{- include "latr.accountLabels" $ctx | nindent 4 }}
spec:
  {{- if $.Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ $.Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if $.Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ $.Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "latr.accountSelectorLabels" $ctx | nindent 6 }}
{{- end }}
{{- end }}
